vegan = [
    'apricots',
    'rice',
    'mangos',
    'rutabagas',
    'leeks',
    'cassava',
    'margarine',
    'apple juice',
    'garlic',
    'avocados',
    'edamame',
    'water',
    'sweet potatos',
    'lemons',
    'strawberries',
    'oat bran',
    'fruit cocktail',
    'tapioca',
    'corn',
    'salad dressing',
    'mushrooms',
    'tomatillos',
    'wheat flour',
    'cranberry juice',
    'oranges',
    'pepperoni',
    'dates',
    'blackberries',
    'chili',
    'peanut spread',
    'salad dressing',
    'peppers',
    'rice flour',
    'potatoes',
    'heart of palm',
    'oil',
    'rice noodles',
    'aspargus',
    'radicchio',
    'maraschino cherrie',
    'peas',
    'lemonade',
    'yam'
    'arugula',
    'lemon juice',
    'lemon juice from concentrate',
    'cauliflower',
    'brussel sprouts',
    'sweet potato',
    'buckwheat flower',
    'pepper',
    'carrots',
    'lima beans',
    'pomegranate juice',
    'syrup',
    'prune juice',
    'celery',
    'limes',
    'soy flour',
    'couscous',
    'kiwifruit',
    'figs',
    'pineapple',
    'spices',
    'spinach',
    'bulgur',
    'watermelon',
    'taco shells',
    'hominy',
    'tomatoes',
    'grapefruit',
    'radishes',
    'lime juice',
    'basil',
    'cocoa',
    'lentils',
    'lemon peel',
    'onion rings',
    'parsley',
    'grapefruit juice',
    'malt beverage',
    'olives',
    'cornmeal',
    'beans',
    'mustard greens',
    'cherries',
    'turnip greens',
    'tofu',
    'cranberries',
    'grape leaves',
    'blueberries',
    'beets',
    'grapes',
    'egg substitute',
    'chives',
    'salt',
    'apples',
    'artichokes',
    'raspberries',
    'kale',
    'cranberry juice cocktail',
    'corn flour',
    'currants',
    'potato puffs',
    'okra',
    'pickles',
    'orange juice',
    'pears',
    'juice',
    'syrups',
    'tangerine juice',
    'peaches',
    'broccoli',
    'grape juice',
    'pineapple juice',
    'bamboo shoots',
    'tomato juice',
    'mung beans',
    'popcorn',
    'quinoa',
    'pickle relish',
    'soymilk',
    'nectarines',
    'wild rice',
    'rye flour',
    'capers',
    'pumpkin'
]

